plugins:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  Exclude:
    - "bin/**/*"
    - "test/dummy/**/*"
    - "vendor/**/*"

Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    - "*.gemspec"
